paths:
  /api/comment/list:
    get:
      tags:
        - comment
      description: 게시글의 고유 ID로 그 게시글의 댓글 목록을 불러옴
      parameters:
        - name: id
          in: query
          description: 댓글 목록을 불러올 게시글의 고유 ID
          required: true
          schema:
            type: number
            default: 5
      responses:
        200:
          description: 성공적으로 게시글에 대한 댓글 목록을 불러옴
        400:
          description: 해당 게시글의 댓글 목록을 불러오지 못함
