paths:
  /api/board/likest:
    get:
      tags:
        - board
      description: 전체 게시글 중에 Like를 가장 많이 받은 게시글을 불러옴
      responses:
        200:
          description: 가장 Like를 많이 받은 10개의 게시글에 대한 메타 데이터를 받음
        400:
          description: 가장 Like를 많이 받은 게시글을 불러오지 못함
