paths:
  /api/board/list:
    get:
      tags:
        - board
      description: Board 이름와 Pagination을 위한 index에 맞는 게시글의 메타 데이터 10개를 받음
      parameters:
        - name: index
          in: query
          description: Pagination에 사용할 index
          required: true
          schema:
            type: string
            default: "0"
        - name: board
          in: query
          description: 게시글을 불러들이고자 하는 Board 이름
          required: true
          schema:
            type: string
            default: board one
      responses:
        200:
          description: Pagination index에 맞는 게시글의 메타 데이터 10개
        400:
          description: 모종의 이유로 요청에 대한 응답을 제대로 받지 못함
