paths:
  /api/board/recent:
    get:
      tags:
        - board
      description: 전체 게시글 중에 최근 게시된 10개의 게시글을 불러옴
      responses:
        200:
          description: 가장 최근에 게시된 10개의 게시글에 대한 메타 데이터를 받음
        400:
          description: 최근 게시된 게시글을 불러오지 못함
