paths:
  /api/board/size:
    get:
      tags:
        - board
      description: 해당 Board에 작성된 게시글의 총 수를 불러옴
      parameters:
        - name: board
          in: query
          description: 게시글 수를 불러올 Board 이름
          required: true
          schema:
            type: string
            default: Board one
        - name: search
          in: query
          description: 검색하고자 하는 키워드
          required: false
          schema:
            type: string
            default: test
      responses:
        200:
          description: 조건에 맞는 Board의 게시글의 총 수를 받음
        400:
          description: 요청에 대한 처리를 제대로 하지 못함, number 형식이므로 N/A의 의미의 -1 반환
