paths:
  /api/board/viewest:
    get:
      tags:
        - board
      description: 전체 게시글 중에 가장 조회수가 높은 10개의 게시글을 불러옴
      responses:
        200:
          description: 전체 게시글 중 가장 조회수가 높은 10개의 게시글에 대한 메타 데이터를 받음
        400:
          description: 모종의 이유로 요청에 대한 응답이 제대로 이루어지지 않음
